version: '3.4'

services:
  Yah.hub.mercadolivre.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  Yah.hub.scheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  Yah.hub.magalu.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  Yah.hub.b2w.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  Yah.hub.integrationmonitor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  Yah.hub.broker.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  Yah.hub.netshoes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  Yah.hub.viavarejo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

