apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: marketplace-${ENVIRONMENTLOWER}-${MARKETPLACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marketplace-${ENVIRONMENTLOWER}-${MARKETPLACE}
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 75