apiVersion: v1
kind: Service
metadata:
  name: marketplace-${ENVIRONMENTLOWER}-${MARKETPLACE}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: marketplace-${ENVIRONMENTLOWER}-${MARKETPLACE}.Yah.com.br
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    #- name: https
    #  port: 443
    #  targetPort: 443
    #  protocol: TCP
  type: LoadBalancer
  selector:
    app: marketplace-${ENVIRONMENTLOWER}-${MARKETPLACE}